// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frequentationPB/frequentation.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FrequentationRequest struct {
	Zipcode              string   `protobuf:"bytes,1,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrequentationRequest) Reset()         { *m = FrequentationRequest{} }
func (m *FrequentationRequest) String() string { return proto.CompactTextString(m) }
func (*FrequentationRequest) ProtoMessage()    {}
func (*FrequentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0a385a1ce38c60, []int{0}
}

func (m *FrequentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequentationRequest.Unmarshal(m, b)
}
func (m *FrequentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequentationRequest.Marshal(b, m, deterministic)
}
func (m *FrequentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequentationRequest.Merge(m, src)
}
func (m *FrequentationRequest) XXX_Size() int {
	return xxx_messageInfo_FrequentationRequest.Size(m)
}
func (m *FrequentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FrequentationRequest proto.InternalMessageInfo

func (m *FrequentationRequest) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

type FrequentationResponse struct {
	Value                []*FrequentationResponse_Value `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FrequentationResponse) Reset()         { *m = FrequentationResponse{} }
func (m *FrequentationResponse) String() string { return proto.CompactTextString(m) }
func (*FrequentationResponse) ProtoMessage()    {}
func (*FrequentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0a385a1ce38c60, []int{1}
}

func (m *FrequentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequentationResponse.Unmarshal(m, b)
}
func (m *FrequentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequentationResponse.Marshal(b, m, deterministic)
}
func (m *FrequentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequentationResponse.Merge(m, src)
}
func (m *FrequentationResponse) XXX_Size() int {
	return xxx_messageInfo_FrequentationResponse.Size(m)
}
func (m *FrequentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FrequentationResponse proto.InternalMessageInfo

func (m *FrequentationResponse) GetValue() []*FrequentationResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type FrequentationResponse_Value struct {
	UicCode              string   `protobuf:"bytes,1,opt,name=uic_code,json=uicCode,proto3" json:"uic_code,omitempty"`
	A2015                int32    `protobuf:"varint,2,opt,name=a2015,proto3" json:"a2015,omitempty"`
	A2016                int32    `protobuf:"varint,3,opt,name=a2016,proto3" json:"a2016,omitempty"`
	A2017                int32    `protobuf:"varint,4,opt,name=a2017,proto3" json:"a2017,omitempty"`
	A2018                int32    `protobuf:"varint,5,opt,name=a2018,proto3" json:"a2018,omitempty"`
	A2019                int32    `protobuf:"varint,6,opt,name=a2019,proto3" json:"a2019,omitempty"`
	A2020                int32    `protobuf:"varint,7,opt,name=a2020,proto3" json:"a2020,omitempty"`
	A2021                int32    `protobuf:"varint,8,opt,name=a2021,proto3" json:"a2021,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrequentationResponse_Value) Reset()         { *m = FrequentationResponse_Value{} }
func (m *FrequentationResponse_Value) String() string { return proto.CompactTextString(m) }
func (*FrequentationResponse_Value) ProtoMessage()    {}
func (*FrequentationResponse_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0a385a1ce38c60, []int{1, 0}
}

func (m *FrequentationResponse_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequentationResponse_Value.Unmarshal(m, b)
}
func (m *FrequentationResponse_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequentationResponse_Value.Marshal(b, m, deterministic)
}
func (m *FrequentationResponse_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequentationResponse_Value.Merge(m, src)
}
func (m *FrequentationResponse_Value) XXX_Size() int {
	return xxx_messageInfo_FrequentationResponse_Value.Size(m)
}
func (m *FrequentationResponse_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequentationResponse_Value.DiscardUnknown(m)
}

var xxx_messageInfo_FrequentationResponse_Value proto.InternalMessageInfo

func (m *FrequentationResponse_Value) GetUicCode() string {
	if m != nil {
		return m.UicCode
	}
	return ""
}

func (m *FrequentationResponse_Value) GetA2015() int32 {
	if m != nil {
		return m.A2015
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2016() int32 {
	if m != nil {
		return m.A2016
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2017() int32 {
	if m != nil {
		return m.A2017
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2018() int32 {
	if m != nil {
		return m.A2018
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2019() int32 {
	if m != nil {
		return m.A2019
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2020() int32 {
	if m != nil {
		return m.A2020
	}
	return 0
}

func (m *FrequentationResponse_Value) GetA2021() int32 {
	if m != nil {
		return m.A2021
	}
	return 0
}

func init() {
	proto.RegisterType((*FrequentationRequest)(nil), "frequentation.FrequentationRequest")
	proto.RegisterType((*FrequentationResponse)(nil), "frequentation.FrequentationResponse")
	proto.RegisterType((*FrequentationResponse_Value)(nil), "frequentation.FrequentationResponse.Value")
}

func init() {
	proto.RegisterFile("frequentationPB/frequentation.proto", fileDescriptor_5c0a385a1ce38c60)
}

var fileDescriptor_5c0a385a1ce38c60 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2b, 0x4a, 0x2d,
	0x2c, 0x4d, 0xcd, 0x2b, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x70, 0xd2, 0x47, 0xe1, 0xeb, 0x15,
	0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xf1, 0xa2, 0x08, 0x4a, 0x49, 0xa6, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4,
	0xea, 0x83, 0x25, 0x93, 0x4a, 0xd3, 0xf4, 0x13, 0xf3, 0x2a, 0x21, 0x2a, 0x95, 0x0c, 0xb8, 0x44,
	0xdc, 0x90, 0xd5, 0x06, 0x81, 0xd8, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0x55, 0x99, 0x05, 0xc9,
	0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0xd2, 0x0c, 0x26, 0x2e,
	0x51, 0x34, 0x2d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x0e, 0x5c, 0xac, 0x65, 0x89, 0x39,
	0xa5, 0x20, 0x1d, 0xcc, 0x1a, 0xdc, 0x46, 0x5a, 0x7a, 0xa8, 0x4e, 0xc3, 0xaa, 0x49, 0x2f, 0x0c,
	0xa4, 0x23, 0x08, 0xa2, 0x51, 0x6a, 0x0f, 0x23, 0x17, 0x2b, 0x58, 0x40, 0x48, 0x92, 0x8b, 0xa3,
	0x34, 0x33, 0x39, 0x1e, 0xd9, 0x01, 0xa5, 0x99, 0xc9, 0xce, 0xf9, 0x29, 0xa9, 0x42, 0x22, 0x5c,
	0xac, 0x89, 0x46, 0x06, 0x86, 0xa6, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10, 0x0e, 0x4c,
	0xd4, 0x4c, 0x82, 0x19, 0x21, 0x6a, 0x06, 0x13, 0x35, 0x97, 0x60, 0x41, 0x88, 0x9a, 0xc3, 0x44,
	0x2d, 0x24, 0x58, 0x11, 0xa2, 0x16, 0x30, 0x51, 0x4b, 0x09, 0x36, 0x84, 0xa8, 0x25, 0x54, 0xd4,
	0xc8, 0x40, 0x82, 0x1d, 0x2e, 0x6a, 0x64, 0x00, 0x13, 0x35, 0x94, 0xe0, 0x40, 0x88, 0x1a, 0x1a,
	0x25, 0x73, 0xf1, 0xa2, 0x78, 0x52, 0x28, 0x88, 0x8b, 0x25, 0x28, 0x35, 0x31, 0x45, 0x48, 0x85,
	0x98, 0xa0, 0x90, 0x22, 0x4a, 0x95, 0x93, 0x60, 0x14, 0x3f, 0x5a, 0x12, 0x48, 0x62, 0x03, 0xc7,
	0xa5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x79, 0xba, 0xf8, 0x04, 0x1c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FrequentationClient is the client API for Frequentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FrequentationClient interface {
	Read(ctx context.Context, in *FrequentationResponse, opts ...grpc.CallOption) (*FrequentationResponse, error)
}

type frequentationClient struct {
	cc grpc.ClientConnInterface
}

func NewFrequentationClient(cc grpc.ClientConnInterface) FrequentationClient {
	return &frequentationClient{cc}
}

func (c *frequentationClient) Read(ctx context.Context, in *FrequentationResponse, opts ...grpc.CallOption) (*FrequentationResponse, error) {
	out := new(FrequentationResponse)
	err := c.cc.Invoke(ctx, "/frequentation.Frequentation/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrequentationServer is the server API for Frequentation service.
type FrequentationServer interface {
	Read(context.Context, *FrequentationResponse) (*FrequentationResponse, error)
}

// UnimplementedFrequentationServer can be embedded to have forward compatible implementations.
type UnimplementedFrequentationServer struct {
}

func (*UnimplementedFrequentationServer) Read(ctx context.Context, req *FrequentationResponse) (*FrequentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterFrequentationServer(s *grpc.Server, srv FrequentationServer) {
	s.RegisterService(&_Frequentation_serviceDesc, srv)
}

func _Frequentation_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrequentationResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrequentationServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frequentation.Frequentation/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrequentationServer).Read(ctx, req.(*FrequentationResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _Frequentation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frequentation.Frequentation",
	HandlerType: (*FrequentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Frequentation_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frequentationPB/frequentation.proto",
}
